firmware:
  image:
    name: docker.i74.de:5000/gcvideo-build-system
  stage: build
  before_script:
    - source /opt/Xilinx/14.7/ISE_DS/settings64.sh
    - export PATH=$PATH:/root/zpugcc/toolchain/install/bin
  script: 
    - HDL/gcvideo_dvi/build-all.sh
  artifacts:
    paths:
    - HDL/gcvideo_dvi/binaries/*.zip
  tags:
    - xilinx-ise
